require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
--> ...
require "user.notify"
require "user.colorscheme"
require "user.toggleterm"
require "user.whichkey"

require "user.alpha"
require "user.project"
require "user.indent-blankline"
require "user.impatient"
--> ...

require "user.neorg"
-- require "user.markdown_preview"
